### ISSUE TITLE
PMID

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/donders-institute.github.io#11]
TBD: Does the PMID add sufficient information if we also have a PID?

**Comment by robertoostenveld** [comment]
@EricMaris @hurngchunlee 

The PMID allows for using the Pubmed API to automatically fetch information that the CMS could display. Another PID (e.g. handle) would not allow us to fetch that information. But another PID would be a better pointer to the actual document, whereas the PMID is only a pointer to another database with (meta)information about the document.

See http://www.ncbi.nlm.nih.gov/books/NBK25501/

Especially in the context of SEO (search engine optimization) of the DSC it would be interesting to display the abstract+keywords from pubmed. Note that the specific "TBD" item relates to the SIC, so here it might not be needed. 

Nevertheless, I suggest we keep both. With regards to "form entry data validation" it would be nice (and sufficient) to check that one of the IDs is provided. If we make them optional, I would also opt for adding  arXiv. 

On a side track: I realize that both identifiers might pose problems with regards to the timing of editing these fields and closing (i.e. the IDs might be assigned considerably later than acceptance of publication).

**Comment by hurngchunlee** [comment]
For RDC and DSC, there is an attribute called "associatedPublication" and it is repeatable.  I suggest to implement the PID's related to (e-)publication using this attribute.  The attribute can consist of two parts:

1. the identifier
2. the scheme to which the identifier is meaningful (e.g. `DOI`, `PMID`, `arXiv`, and a pre-defined list)

An example referring to this [paper] (http://www.ncbi.nlm.nih.gov/pubmed/26730729) looks like this:

```
associatedPublication = "scheme=PMID%identifier=26730729"
associatedPublication = "scheme=DOI%identifier=10.1371/journal.pone.0146259"
```

**Comment by robertoostenveld** [comment]
The proposed representation looks fine to me. Whether we do something smart (*) with it in the views provided by the CMS is to be posted on a (future) wish list. 

*) e.g. URL-ify or query for associated data in the respective external databases such as pubmed

If it were a structured DB rather than a key-value store, we would probably end up with a "publication" table and point to entries in that to avoid duplication.  

I changed the text into "Following publication, the researcher is required to add the DOI as the persistent identifier (PID) of the published manuscript. Besides the DOI, the researcher can also provide the Pubmed ID (PMID) or arXiv identifier."

mac011> git commit researcher.md 
[master 71908da] clarify PMID, see https://github.com/Donders-Institute/donders-institute.github.io/issues/11
 1 file changed, 1 insertion(+), 6 deletions(-)
mac011> git push
...
