### ISSUE TITLE
pre-registration

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/donders-institute.github.io#12]
TBD: I propose to remove 9.3.4. The pre-registration already is documented by the journal.

**Comment by robertoostenveld** [comment]
No, I prefer to keep it in. It would be good to have pointers to e.g.

https://clinicaltrials.gov
https://aspredicted.org

**Comment by EricMaris** [comment]
OK, we keep it in. Actually, I contributed it initially, but then started doubting about its necessity when tried to minimalize the protocol.
