### ISSUE TITLE
informed consent forms on paper

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/donders-institute.github.io#16]
section 8.2.4.1 item 2  (DAQ requirements in case of human subjects)

now states "2.	The researcher must archive the signed informed consent forms (i.e., the paper forms) outside the digital RDM archive. These forms must allow for the de-identified data to be shared via a data sharing collection (DSC). If the researcher plans to share the data of this DAC together with data of the same participants in other DACs, then the signed informed consent forms must mention this linked sharing.
... The precise archiving protocol for the signed informed consent forms (where to hand in the forms, where they will be archived, ...) differs according to DI center, and the center management is responsible for communicating this protocol."

I don't think this should be part of the protocol.  In the section 4-Context we state 

"The context of this protocol is the Research Data Management (RDM) at the Donders Institute (DI), which involves interaction with a digital data repository. This protocol describes how researchers must interact with this repository."

I don't think that this protocol should describe the (existing or future) requirements of proper conduct by researchers outside the ICT system. Researchers have to archive the paper forms already at this moment (according to center specific guidelines), and *this* protocol does not change anything in that respect.

**Comment by EricMaris** [comment]
I agree, and have removed from the protocol all sentences that pertain to the protocol w.r.t. the paper informed consent forms.
