### ISSUE TITLE
creating user accounts not possible for ou_admin

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/donders-institute.github.io#18]
The rights and responsibilities of research administrators involve the following:

1.	Initiating, initializing and managing collections.
2.	Authorizing users at the center level.
3.	Creating, managing and linking user accounts.

TBD: in the previous section, it states "creating" user accounts. But the ou_admin cannot create user accounts in the RDM, only u- and e-number accounts.

**Comment by robertoostenveld** [comment]
hmm, I realize that this relates to section 8 (Creating, Managing and Linking User Accounts).

Contrary to what I wrote above, there can be the need to create accounts besides u- and e-numbers.

@hurngchunlee are there currently user stories that relate to account creation?

**Comment by hurngchunlee** [comment]
I don't get it.  Are we talking about account that can bypass IdP authentication?

**Comment by robertoostenveld** [comment]
Yes, that is what it related to (but see below). For the process of creating a e-number account we don't need anything implemented in the CMS, that only requires documentation.

...

It seems that the respective sections of text in the protocol have been removed. That means that the issue is resolved.
