### ISSUE TITLE
protocol for initiating RDC

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/donders-institute.github.io#21]
Is the Protocol Specific for Research Documentation Collections to be defined at the institute level or at the center level?

At the institute level we know (implicitly) that "around" the publication work needs to be done. I have now added some text to section 6.3.1, @EricMaris please review.

**Comment by EricMaris** [comment]
I also added some text, mainly pertaining to when the RDC must be initiated. I have provided this information also in 9.2.2 of the protocol for researchers, because they are the ones that should follow these instructions. I did something similar for the DSC (10.2.2 in the protocol for researchers).

@robertoostenveld please review

**Comment by robertoostenveld** [comment]
9.2.2 of researcher.md now states that "The RDC is not to be used for storing processed data."

**I disagree: researchers should be allowed to upload results of processing to the RDC. If processed data is not allowed, it would only contain analysis scripts, figures and the textual interpretation contained in the manuscript. **

Note: Ideally people would indeed implement their analysis such that (re)running scripts on the original data (from the DAQ) would (re)produce the results in the manuscript. But that will often not be feasible.

**Comment by EricMaris** [comment]
I agree with your remark. I now tried to make my point in a way that should be feasible for all cases in practice (at the expense of a bit of vagueness though ...). This is the new paragraph (which you can also find under 9.2.2.):

_The RDC is _not_ to be used for storing all the processed data that are generated as a part of the data analysis. For that purpose, typically, one should use the storage that is part of a computing environment (either a desktop or a server) to which most researchers have access. Processed data that can be added to the RDC should have the character of temporary or final results._

**Comment by robertoostenveld** [comment]
agreed.
