### ISSUE TITLE
DCX_employee

### ISSUE THREAD

**Issue by EricMaris** [Donders-Institute/donders-institute.github.io#25]
I propose to change the label OU_member by OU_employee, which would correspond to DCX_employee as it is in the protocols. The reason for this request is that a center may have members that are not employees in the sense that they do not have the right to be added as collection manager.

**Comment by robertoostenveld** [comment]
Agreed, I think that is a good match with the formal requirements. @hurngchunlee, does this mean that the corresponding string/variable needs to be search-and-replaced in the iRODS and CMS code?

**Comment by hurngchunlee** [comment]
The term "OU_member" or "OU_employee" is not visible anywhere to end-users in iRODS or CMS.  Internally, it's related to the iRODS user groups internally called  `dccn/dcc/dcn_s/dcn_m_user`.  The group is just a technical implementation for controlling the user's access permission.

From the end-user's perspective, the "OU_employee" is reflected by the "organisationalUnit" attribute on user profile.  So far, the display of this attribute on CMS is not implemented yet.

Therefore, I don't think there is a need to change code/string in iRODS or CMS.
