### ISSUE TITLE
FSW ethical approval identifier

### ISSUE THREAD

**Issue by EricMaris** [Donders-Institute/donders-institute.github.io#28]
@robertoostenveld 

Ik heb Marianne Blijleven gesproken.

De syntax van een FSW ethische goedkeuring identifier: “ECSW”YYYY-DDMM-XXX.

Hierbij is "ECSW" een vaste string, en is XXX een volgnummer dat doorloopt over de jaren. Ze zitten nu rond 330. Ik denk wel dat het slim is om hier 4 cijfers voor te reserveren.

**Comment by robertoostenveld** [comment]
Ok, I documented it on http://donders-institute.github.io/rdm-wiki/en/#!faq/dac.md and discussed it with @hurngchunlee. Entry on the form and validation will consist of 
1) selection of the ethics board (from a controlled vocabulary, including a.o. ECSW)
2) entry of the subsequent number, where validation will ensure the correct format (and dashes)

I have corrected the use of ECSC -> ECSW
I also updated the password requirements (as discussed over email)

mac011> git commit -a
[master 8d77116] updated section on password and on ethics IDs
 1 file changed, 14 insertions(+), 15 deletions(-)
mac011> git push
X11 forwarding request failed on channel 0
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 910 bytes | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
To git@github.com:Donders-Institute/donders-institute.github.io.git
   755a593..8d77116  master -> master

mac011> git commit -a
[master 9fc0c81] one more typo fixed
 1 file changed, 2 insertions(+), 2 deletions(-)
mac011> git push
X11 forwarding request failed on channel 0
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 562 bytes | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
To git@github.com:Donders-Institute/donders-institute.github.io.git
   8d77116..9fc0c81  master -> master

**Comment by robertoostenveld** [comment]
@hurngchunlee https://github.com/donders-research-data-management/rdm-control-vocabularies/ should be updated to reflect the full list of ethics boards from 
https://github.com/Donders-Institute/donders-institute.github.io/blob/master/rdm-wiki/en/guides/ethics.md
and the summary of 
https://github.com/Donders-Institute/donders-institute.github.io/blob/master/rdm-wiki/en/faq/dac.md

**Comment by hurngchunlee** [comment]
The ethics boards are summarized into another repository after the sprint planning session, and a followup discussion with Robert: https://github.com/donders-research-data-management/rdm-ontology/blob/master/vocabulary/ethics_review_board.json
