### ISSUE TITLE
guidelines for ethics

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/donders-institute.github.io#4]
TBD1: I propose to also add the following documents to this Github-hosted wiki: guidelines for deciding about the appropriate ethical review board, the template informed consent forms, the template information brochures. When realized, we can refer to these documements from inside the wiki. This must also be discussed with Sabine K and Miriam K, because they must be comfortable working with it.

**Comment by robertoostenveld** [comment]
This needs to be done, but is not part of the protocol. I suggest add this to the existing page
http://donders-institute.github.io/rdm-wiki/en/#!guides/ethics.md
and making the Donders guidelines the core content and moving the existing content of the page to an appendix type of format to the bottom of the page. 

I assigend @EricMaris to do this.

**Comment by robertoostenveld** [comment]
mac011> git commit researcher.md 
[master d50061a] removed TBD item that is not to be solved in this document. see https://github.com/Donders-Institute/donders-institute.github.io/issues/4
 1 file changed, 3 deletions(-)
mac011> git push
X11 forwarding request failed on channel 0
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 618 bytes | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
To git@github.com:Donders-Institute/donders-institute.github.io.git
   a82b274..d50061a  master -> master

**Comment by EricMaris** [comment]
I agree that the documents mentioned in the TBD (first) belong to the ethics package, and does fits in with the current content of ethics.md. However, ethics.md is grouped under "Data Access", where it doesn't fit IMO. 

I propose we make a new group "Legal Aspects" under which we organise the following:
1. Guidelines for deciding about the ethical review board
2. Template informed consent forms
3. Template information brochures
4. Decision tree for Data Use Agreements
5. Data Use Agreements

**Comment by robertoostenveld** [comment]
I don't think that we should have too many pages and menu items for now. Better a few pages and organize the content on the pages. We can always cut them up later, but for now we will have ourselves a better overview if we use the structure within the page. 

I just reorganized the navigation top level menu into 

Users
|-> before
|-> during 
|-> after

to indicate the three most obvious time windows: before you use the RDM you should organize your ethics, during acquisition, analysis and publishing you should use the CMS+iRods, after publishing the paper+data you should advertise it.

Under the before I will add a section with the items you just mentioned.
